version: "2"

networks:
    default:
        external:
            name: rede_gearman
services:
    gearman:
        image: "lucaslz/ubuntu-gearman"
        container_name: gearman-server
        ports:
            - 4731:4730
        networks:
            default:
                ipv4_address: 172.25.0.2
    consumer_one:
        image: "lucaslz/ubuntu-gearman-worker-php"
        container_name: gearman-consumer-one
        volumes:
            - ./:/var/www/scripts/
        entrypoint: "php /var/www/scripts/consumer.php"
        networks:
            default:
                ipv4_address: 172.25.0.3
    consumer_two:
        image: "lucaslz/ubuntu-gearman-worker-php"
        container_name: gearman-consumer-two
        volumes:
            - ./:/var/www/scripts/
        entrypoint: "php /var/www/scripts/consumer.php"
        networks:
            default:
                ipv4_address: 172.25.0.4